DROP SCHEMA IF EXISTS schevo CASCADE;
CREATE SCHEMA IF NOT EXISTS schevo;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA schevo FROM schevo;
ALTER DEFAULT PRIVILEGES IN SCHEMA schevo REVOKE SELECT, INSERT, UPDATE ON TABLES FROM schevo;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA schevo FROM schevo;
ALTER DEFAULT PRIVILEGES IN SCHEMA schevo REVOKE EXECUTE ON FUNCTIONS FROM schevo;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA schevo FROM schevo;
ALTER DEFAULT PRIVILEGES IN SCHEMA schevo REVOKE USAGE, SELECT ON SEQUENCES FROM schevo;
DROP USER IF EXISTS schevo;

CREATE USER schevo WITH PASSWORD 'Schevo!2025';
GRANT USAGE, CREATE ON SCHEMA schevo TO schevo;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA schevo TO schevo;
ALTER DEFAULT PRIVILEGES IN SCHEMA schevo GRANT SELECT, INSERT, UPDATE ON TABLES TO schevo;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA schevo TO schevo;
ALTER DEFAULT PRIVILEGES IN SCHEMA schevo GRANT EXECUTE ON FUNCTIONS TO schevo;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA schevo TO schevo;
ALTER DEFAULT PRIVILEGES IN SCHEMA schevo GRANT USAGE, SELECT ON SEQUENCES TO schevo;
